nacos:
  client:
    namespace_id: "public" #nacos命名空间
    timeout_ms: 10000 #http请求超时时间，单位毫秒
    listen_interval: 30000 #监听间隔时间，单位毫秒（仅在ConfigClient中有效）
    beat_interval: 5000 #心跳间隔时间，单位毫秒（仅在ServiceClient中有效）
    endpoint: "" #获取nacos节点ip的服务地址
    cacheDir: "data/nacos/cache" #缓存目录
    logDir: "data/nacos/log" #日志目录
    update_thread_num: 20 #更新服务的线程数
    not_load_cache_at_start: true #在启动时不读取本地缓存数据，true--不读取，false--读取
    update_cache_when_empty: true #当服务列表为空时是否更新本地缓存，true--更新,false--不更新
    username: "nacos"
    password: "nacos"

  server:
    server1:
      ip_addr: "192.168.88.222" #nacos服务的ip地址
      port: 8848 #nacos服务端口
      context_path: "/nacos" #nacos服务的上下文路径，默认是“/nacos”

discovery:
  group_name: "DEFAULT_GROUP"
  cluster_name: "DEFAULT"
  weight: 10
  enable: true
  healthy: true
  ephemeral: true

application:
  name: "saas-demo.go"

http:
  port: 9901
  network: "tcp"
  read_timeout: "5s"
  write_timeout: "5s"